export const String = {
    termOfUse : 'These Terms of Use ("Terms") govern your access to and use of the Kathavachak website and mobile application (collectively referred to as the "Service"). By accessing or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, please do not use the Service',
    title_point1: '1.  Use of the Service',
    title_point2: '2.  User Content:',
    title_point3: '3.  Intellectual Property:',
    title_point4: '4.  Third-Party Links:',
    title_point5: '5.  Disclaimer of Warranties:',
    title_point6: '6.  Limitation of Liability:',
    title_point7: '7.  Governing Law:',
    title_point8: '8.  Changes to these Terms:',
    title_point9: '9.  Contact Us:',
    point1_subPoint_1: `You must be at least 13 years old to use the Service. If you are under 13, you may only use the Service with parental or guardian consent.`,
    point1_subPoint_2:`You agree to use the Service only for lawful purposes and in compliance with these Terms and all applicable laws and regulations.`,
    point1_subPoint_3:`You are responsible for all activities conducted through your account, and you agree not to share your account credentials with others.`,
    point2_subPoint_1: `You retain ownership of any content you create, upload, or share on the Service, but you grant Kathavachak a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, adapt, publish, translate, distribute, and display such content for the purpose of operating and improving the Service.`,
    point2_subPoint_2:`You agree not to upload or share any content that violates the rights of others, including but not limited to intellectual property rights, privacy rights, or publicity rights.`,
    point3_subPoint_1:`All content and materials available on the Service, including but not limited to text, graphics, logos, images, audio clips, and software, are owned by Kathavachak or its licensors and are protected by copyright, trademark, and other intellectual property laws.`,
    point3_subPoint_2:`You agree not to modify, reproduce, distribute, transmit, or publicly display any content from the Service without the prior written consent of Kathavachak.`,
    point4_subPoint_1:`The Service may contain links to third-party websites or resources that are not owned or controlled by Kathavachak. We are not responsible for the content or practices of any third-party websites or resources.`,
    point4_subPoint_2:`You acknowledge and agree that Kathavachak is not liable for any loss or damage arising from your use of any third-party websites or resources.`,
    point5_subPoint_1:`The Service is provided on an "as-is" and "as available" basis, without warranties of any kind, express or implied. Kathavachak disclaims all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement`,
    point5_subPoint_2:`Kathavachak does not warrant that the Service will meet your requirements or be uninterrupted, error-free, or secure.`,
    point6_subPoint_1:`Kathavachak shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill, arising from your use of or inability to use the Service.`,
    point7_subPoint_1:`These Terms shall be governed by and construed in accordance with the laws of [insert jurisdiction]. Any dispute arising out of or relating to these Terms shall be subject to the exclusive jurisdiction of the courts located in India.`,
    point8_subPoint_1:`Kathavachak reserves the right to modify or update these Terms at any time without prior notice. Your continued use of the Service after the posting of the revised Terms constitutes your acceptance of the changes.`,
    point9_subPoint_1:`If you have any questions, concerns, or feedback about these Terms, please contact us at team@kathavachak.in .`,
    endingLine: `Please read these Terms carefully before using the Service. If you have any questions or concerns, please contact us.`
}