export const Images = {
  image: require('../../assets/images/image.png'),
  play: require('../../assets/images/play.png'),
  audioBookImage: require('../../assets/images/sampleAudioBook.png'),
  audioBookImage2: require('../../assets/images/sampleAudioBook_2.png'),
  audioBookImage3: require('../../assets/images/sampleAudioBook_3.png'),
  audioBookImage4: require('../../assets/images/sampleAudioBook_4.png'),
  audioBookImage5: require('../../assets/images/sampleAudioBook_5.png'),
  playButtonSymbol: require('../../assets/images/PlayButton.png'),
  userProfile: require('../../assets/images/user.png'),
  cross: require('../../assets/images/cross.png'),
  send: require('../../assets/images/send.png'),
  kathaVachakLogo: require('../../assets/images/kathavachak.png'),
  imagePlaceholder: require('../../assets/images/placeholder.jpeg'),
  microphone: require('../../assets/images/microphone.png'),
  searchIcon: require('../../components/atoms/SearchBar/search.png'),
  noData: require('../../assets/images/noData.json'),
  kathaVachakBanner: require('../../assets/images/kathaVachakBanner.png'),
  readLoaderLottie: require('../../assets/images/ReadingLoader.json'),
};
